class Params:
    SYMBOL = "symbol"
    START_TIME = "startTime"
    END_TIME = "endTime"


class Coins:
    USDT = "USDT"
    BTC = "BTC"
    SC = "SC"
    STMX = "STMX"
    COS = "COS"
    REEF = "REEF"
    TCT = "TCT"
    XVG = "XVG"
    AKRO = "AKRO"
    CELR = "CELR"
    IOST = "IOST"

    CKB = "CKB"
    DGB = "DGB"
    ZIL = "ZIL"
    TRX = "TRX"
    VET = "VET"
    RVN = "RVN"
    IOTX = "IOTX"
    CTXC = "CTXC"
    SYS = "SYS"
    NULS = "NULS"
    DUSK = "DUSK"
    FLUX = "FLUX"
    PYR = "PYR"
    MC = "MC"
    REQ = "REQ"
    GXS = "GXS"
    ANT = "ANT"
    LTO = "LTO"
    WAN = "WAN"